---
title: "Equações da volta"
author: "Silvaneo Viera dos Santos Junior"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Queremos calcular $\mathbb{E}[\ln(\phi)]$, $\mathbb{E}[\ln(\mu)]$, $Var[\ln(\phi)]$, $Var[\ln(\mu)]$ e $Cov[\ln(\phi),\ln(\mu)]$.

Usando que a distribuição aproximada de $\phi$ ($\mathcal{G}\left(\frac{n_0+1}{2},n_0\ln\left(\frac{\tau_0}{n_0}\right)-\theta_0\right)$) podemos obter uma expressão aproximada para os valores esperados que dependem apenas de $\phi$:

$$
\begin{aligned}
\mathbb{E}[\ln(\phi)]&\approx \psi\left(\frac{n_0+1}{2}\right)-ln\left(n_0\ln\left(\frac{\tau_0}{n_0}\right)-\theta_0\right)\\
Var[\ln(\phi)]&\approx \psi'\left(\frac{n_0+1}{2}\right)
\end{aligned}
$$

Como visto antes $\mu|\phi \sim \mathcal{IG}(n_0 \phi+1,\phi\tau_0)$ (lembrando que isso não é uma aproximação, essa é a distribuição exata de $\mu|\phi$), daí podemos escrever:

$$
\begin{aligned}
\mathbb{E}[\ln(\mu)]&=-\mathbb{E}[\ln(1/\mu)]=-\mathbb{E}[\mathbb{E}[\ln(1/\mu)|\phi]]\\
&=-\mathbb{E}[\psi(n_0 \phi+1)-ln(\phi\tau_0)]\\
Var[\ln(\mu)]&=Var[\ln(1/\mu)]=\mathbb{E}[Var[\ln(1/\mu)|\phi]]+Var[\mathbb{E}[\ln(1/\mu)|\phi]]\\
&=\mathbb{E}[\psi'(n_0 \phi+1)]+Var[\psi(n_0 \phi+1)-ln(\phi\tau_0)]\\
\mathbb{E}[\ln(\phi)\ln(\mu)]&=-\mathbb{E}[\ln(\phi)\ln(1/\mu)]=-\mathbb{E}[\ln(\phi)\mathbb{E}[\ln(1/\mu)|\phi]]\\
&=-\mathbb{E}[\ln(\phi)(\psi(n_0 \phi+1)-ln(\phi\tau_0))]
\end{aligned}
$$

Talvez seja possível obter expressões analíticas aproximadas para os valores esperados que envolvem $\mu$ usando a distribuição aproximada de $\phi$, mas não cheguei a fazer essas contas. De qualquer forma, essa aproximação não é válida para certos valores dos parâmetros, então temos de usar outra forma para calcular esses valores esperados.

No final fiz todas as contas para a volta usando quadratura gaussiana, uma vez que o custo de se calcular essas integrais numericamente é negligenciável, pois conseguimos escrever todas as integrais como integrais univariadas). Ademais, uma vez calculado os valores esperados, a solução do sistema da volta é trivial, logo não há ganhos significativos de performance ao usar aproximações.
